Repository nocturlab/setup-vlang-action, pull requests merged in 2020-03, with the labels that each got.

#2 Create v build workflow test
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/build_js.yml
  .gitignore
  action.yml
  dist/index.js
  lib/index.js
  lib/installer.js
  lib/system.js
  matchers.json
  package.json
  src/index.ts
  src/installer.ts
  src/system.ts
  tsconfig.json
Labels: feature

#4 WIP: Fix macos build
  .github/workflows/build_js.yml
  dist/index.js
  src/installer.ts
Labels: bug

#6 Replace `VLang` with `V`
  .github/workflows/build_js.yml
  README.md
  action.yml
  dist/index.js
  lib/index.js
  lib/installer.js
  lib/system.js
  src/index.ts
  src/installer.ts
Labels: code refactor

#11 Settings Community informations
  .github/.github/ISSUE_TEMPLATE/bug_report.md
  .github/.github/ISSUE_TEMPLATE/feature_request.md
  .github/.github/ISSUE_TEMPLATE/question.md
  .github/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
Labels: documentation

#13 Add badges of Build and Test pipeline in Readme
  .github/workflows/build_github_action.yml
  .github/workflows/test_github_action.yml
  README.md
Labels: documentation
